### ISSUE TITLE
Docker swarm support

### ISSUE THREAD

**Issue by scholarsmate** [ZettaIO/restic-compose-backup#23]
First of all, let me say this is an **awesome** project.  There are many Restic docker projects out there, but this one seems to have gotten it right from a _design_ perspective.

I'm trying to integrate the service into a docker-compose swarm.  I have this:

```
version: '3'

services:
  backup:
    image: 'zettaio/restic-compose-backup'
    env_file:
      - /etc/restic/restic.env
    volumes:
      # We need to communicate with docker
      - /var/run/docker.sock:/tmp/docker.sock:ro
      # Persistent storage of restic cache (greatly speeds up all restic operations)
      - cache:/cache
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager

volumes:
  cache:
```

I deploy that into a stack that is running Jira, Confluence, 2 PostgreSQL databases and Traefik2.

```
version: '3'

services:

  jira_db:
    image: postgres
    environment:
      - POSTGRES_DB=jiradb
      - POSTGRES_USER=atlassian
      - POSTGRES_PASSWORD=atlassian
      - POSTGRES_ENCODING=UTF8
      - POSTGRES_COLLATE=C
      - POSTGRES_COLLATE_TYPE=C
    command: ["-c", "shared_buffers=256MB", "-c", "max_connections=200"]
    volumes:
      - postgres_jira_data:/var/lib/postgresql/data
    labels:
      - restic-compose-backup.postgres=true

  confluence_db:
    image: postgres
    environment:
      - POSTGRES_DB=confluencedb
      - POSTGRES_USER=atlassian
      - POSTGRES_PASSWORD=atlassian
      - POSTGRES_ENCODING=UTF8
      - POSTGRES_COLLATE=C
      - POSTGRES_COLLATE_TYPE=C
    command: ["-c", "shared_buffers=256MB", "-c", "max_connections=200"]
    volumes:
      - postgres_confluence_data:/var/lib/postgresql/data
    labels:
      - restic-compose-backup.postgres=true

  jira:
    image: atlassian/jira-software
    environment:
      - ATL_PROXY_NAME=jira.${SVC_DOMAIN?}
      - ATL_PROXY_PORT=443
      - ATL_TOMCAT_SCHEME=https
      - ATL_JDBC_URL=jdbc:postgresql://jira_db:5432/jiradb
      - ATL_JDBC_USER=atlassian
      - ATL_JDBC_PASSWORD=atlassian
      - ATL_DB_TYPE=postgres72
      - ALT_DB_DRIVER=org.postgresql.Driver
    volumes:
      - jira_data:/var/atlassian/application-data/jira
      - /etc/localtime:/etc/localtime:ro
    networks:
      - traefik-proxy
      - default
    depends_on:
      - jira_db
    # Control the number of instances deployed
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - restic-compose-backup.volumes=true
        - traefik.enable=true
        - traefik.http.routers.jira.entrypoints=web
        - traefik.http.routers.jira.rule=Host(`jira.${SVC_DOMAIN?}`)
        - traefik.http.services.jira.loadbalancer.server.port=8080
        - traefik.docker.network=traefik-proxy

  confluence:
    image: atlassian/confluence-server:latest
    environment:
      - ATL_PROXY_NAME=confluence.${SVC_DOMAIN?}
      - ATL_PROXY_PORT=443
      - ATL_TOMCAT_SCHEME=https
      - ATL_JDBC_URL=jdbc:postgresql://confluence_db:5432/confluencedb
      - ATL_JDBC_USER=atlassian
      - ATL_JDBC_PASSWORD=atlassian
      - ATL_DB_TYPE=postgresql
    volumes:
      - confluence_data:/var/atlassian/application-data/confluence
      - /etc/localtime:/etc/localtime:ro
    networks:
      - traefik-proxy
      - default
    depends_on:
      - confluence_db
    # Control the number of instances deployed
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - restic-compose-backup.volumes=true
        - traefik.enable=true
        - traefik.http.routers.confluence.entrypoints=web
        - traefik.http.routers.confluence.rule=Host(`confluence.${SVC_DOMAIN?}`)
        - traefik.http.services.confluence.loadbalancer.server.port=8090
        - traefik.docker.network=traefik-proxy

networks:
  traefik-proxy:
    external: true

volumes:
  postgres_jira_data:
  postgres_confluence_data:
  confluence_data:
  jira_data:
```

I have a Restic REST service running in another VM.  When I check the status, it doesn't appear that the backup service can read the labels despite the labels being present.

```
/restic-compose-backup # rcb status
2020-03-03 21:49:11,185 - INFO: Status for compose project 'None'
2020-03-03 21:49:11,185 - INFO: Repository: 'rest:http://10.4.16.6:8000'
2020-03-03 21:49:11,186 - INFO: Backup currently running?: False
2020-03-03 21:49:11,186 - INFO: Checking docker availability
2020-03-03 21:49:11,926 - INFO: ------------------------- Detected Config -------------------------
2020-03-03 21:49:11,927 - INFO: No containers in the project has 'restic-compose-backup.*' label
2020-03-03 21:49:11,927 - INFO: -------------------------------------------------------------------
```

Is reading labels from services running in a swarm stack something that is currently supported by this project?

Thanks.
